mob_id2sid = {
    1: "rock",
    2: "cactus",
    3: "ladybug",
    4: "bee",
    5: "ant_baby",
    6: "ant_worker",
    7: "ant_soldier",
    8: "ant_queen",
    9: "ant_hole",
    10: "beetle",
    11: "hornet",
    12: "centipede",
    14: "centipede_evil",
    16: "centipede_desert",
    18: "square",
    19: "ladybug_dark",
    20: "ladybug_shiny",
    21: "spider",
    22: "scorpion",
    23: "fire_ant_soldier",
    24: "fire_ant_burrow",
    25: "sandstorm",
    26: "bubble",
    27: "bumble_bee",
    28: "shell",
    29: "starfish",
    30: "crab",
    31: "jellyfish",
    32: "digger",
    33: "sponge",
    34: "leech",
    36: "dandelion",
    37: "fire_ant_baby",
    38: "fire_ant_worker",
    39: "fire_ant_queen",
    40: "ant_egg",
    41: "fire_ant_egg",
    42: "fly",
    43: "leafbug",
    44: "mantis",
    45: "termite_baby",
    46: "termite_worker",
    47: "termite_soldier",
    48: "termite_overmind",
    49: "termite_mound",
    50: "termite_egg",
    51: "bush",
    52: "roach",
    53: "moth",
    54: "firefly",
    55: "beetle_hel",
    56: "wasp",
    58: "spider_hel",
    59: "centipede_hel",
    61: "wasp_hel",
    63: "gambler",
    65: "firefly_magic",
    67: "beetle_nazar",
    68: "worm",
    70: "mecha_flower",
    71: "wasp_mecha",
    72: "spider_mecha",
    73: "leafbug_shiny",
    74: "crab_mecha",
    75: "assembler",
    76: "barrel",
    77: "beetle_mummy",
    78: "beetle_pharaoh",
    79: "tomb",
    80: "silverfish",
    81: "garbage",
    82: "ant_soldier_diver",
    83: "ghost",
}

petal_id2sid = {
    1: "basic",
    2: "light",
    3: "rock",
    4: "square",
    5: "rose",
    6: "stinger",
    7: "iris",
    8: "wing",
    9: "missile",
    10: "grapes",
    11: "cactus",
    12: "faster",
    13: "bubble",
    14: "pollen",
    15: "dandelion",
    16: "beetle_egg",
    17: "antennae",
    18: "heavy",
    19: "yin_yang",
    20: "web",
    21: "honey",
    22: "leaf",
    23: "salt",
    24: "rice",
    25: "corn",
    26: "sand",
    27: "pincer",
    28: "yucca",
    29: "magnet",
    30: "yggdrasil",
    31: "starfish",
    32: "pearl",
    33: "lightning",
    34: "jelly",
    35: "claw",
    36: "shell",
    37: "cutter",
    38: "dahlia",
    39: "uranium",
    40: "sponge",
    41: "soil",
    42: "fang",
    43: "third_eye",
    44: "peas",
    45: "stick",
    46: "clover",
    47: "powder",
    48: "air",
    49: "basil",
    50: "orange",
    51: "ant_egg",
    52: "poo",
    53: "relic",
    54: "lotus",
    55: "bulb",
    56: "cotton",
    57: "carrot",
    58: "bone",
    59: "plank",
    60: "tomato",
    61: "mark",
    62: "rubber",
    63: "blood_stinger",
    64: "bur",
    65: "root",
    66: "ankh",
    67: "dice",
    68: "talisman",
    69: "battery",
    70: "amulet",
    71: "compass",
    72: "disc",
    73: "shovel",
    74: "coin",
    75: "chip",
    76: "card",
    77: "moon",
    78: "privet",
    79: "glass",
    80: "corruption",
    81: "orb",
    82: "blueberries",
    83: "magic_cotton",
    84: "magic_stinger",
    85: "magic_leaf",
    86: "magic_cactus",
    87: "magic_eye",
    88: "magic_missile",
    89: "magic_stick",
    90: "coral",
    91: "magic_bubble",
    92: "nazar",
    93: "mimic",
    94: "mjolnir",
    95: "mecha_missile",
    96: "wax",
    97: "golden_leaf",
    98: "cog",
    99: "monstera",
    100: "mecha_antennae",
    101: "laser",
    102: "domino",
    103: "bandage",
    104: "pharaoh_crown",
    105: "totem",
    106: "triangle",
    107: "electric_web",
    108: "sacrifice",
    109: "sawblade",
    110: "clay",
    111: "dust",
    112: "broccoli",
    113: "lentil",
    114: "dead_leaf",
    115: "splitter",
    116: "goggles",
    117: "bean",
    118: "champion_crown",
}

MOB_DROP_POOL = {
    "ant_baby": [{'petal': 'rice', 'baseChance': 0.5}, {'petal': 'light', 'baseChance': 0.25}, {'petal': 'leaf', 'baseChance': 0.15}],
    "ant_egg": [{'petal': 'ant_egg', 'baseChance': 0.25}],
    "ant_hole": [{'petal': 'soil', 'baseChance': 0.25}, {'petal': 'shovel', 'baseChance': 0.2}],
    "ant_queen": [{'petal': 'ant_egg', 'baseChance': 0.5}, {'petal': 'basil', 'baseChance': 0.3}],
    "ant_soldier": [{'petal': 'glass', 'baseChance': 0.3}, {'petal': 'clover', 'baseChance': 0.25}],
    "ant_soldier_diver": [{'petal': 'dead_leaf', 'baseChance': 1}, {'petal': 'bubble', 'baseChance': 1}],
    "ant_worker": [{'petal': 'leaf', 'baseChance': 0.15}, {'petal': 'corn', 'baseChance': 0.15}],
    "assembler": [],
    "barrel": [{'petal': 'mjolnir', 'baseChance': 1}, {'petal': 'uranium', 'baseChance': 0.35}],
    "bee": [{'petal': 'stinger', 'baseChance': 0.25}, {'petal': 'honey', 'baseChance': 0.1}, {'petal': 'pollen', 'baseChance': 0.1}],
    "beetle": [{'petal': 'privet', 'baseChance': 0.5}, {'petal': 'beetle_egg', 'baseChance': 0.25}],
    "beetle_hel": [{'petal': 'dice', 'baseChance': 0.1}, {'petal': 'beetle_egg', 'baseChance': 0.02}, {'petal': 'mark', 'baseChance': 0.01}],
    "beetle_mummy": [{'petal': 'ankh', 'baseChance': 0.25}, {'petal': 'bandage', 'baseChance': 0.15}, {'petal': 'lentil', 'baseChance': 0.05}],
    "beetle_nazar": [{'petal': 'bean', 'baseChance': 1}, {'petal': 'ankh', 'baseChance': 0.04}, {'petal': 'nazar', 'baseChance': 0.01}],
    "beetle_pharaoh": [{'petal': 'ankh', 'baseChance': 1}, {'petal': 'bandage', 'baseChance': 1}, {'petal': 'pharaoh_crown', 'baseChance': 1}],
    "bubble": [{'petal': 'air', 'baseChance': 1}, {'petal': 'bubble', 'baseChance': 0.25}],
    "bumble_bee": [{'petal': 'pollen', 'baseChance': 0.85}, {'petal': 'wax', 'baseChance': 0.55}, {'petal': 'honey', 'baseChance': 0.2}],
    "bush": [{'petal': 'cotton', 'baseChance': 0.5}, {'petal': 'monstera', 'baseChance': 0.25}, {'petal': 'golden_leaf', 'baseChance': 0.005}],
    "cactus": [{'petal': 'cactus', 'baseChance': 0.65}],
    "centipede": [{'petal': 'leaf', 'baseChance': 0.05}, {'petal': 'peas', 'baseChance': 0.05}],
    "centipede_desert": [{'petal': 'salt', 'baseChance': 0.15}, {'petal': 'powder', 'baseChance': 0.05}],
    "centipede_evil": [{'petal': 'iris', 'baseChance': 0.05}, {'petal': 'grapes', 'baseChance': 0.05}],
    "centipede_hel": [{'petal': 'domino', 'baseChance': 0.01}, {'petal': 'mark', 'baseChance': 0.001}],
    "crab": [{'petal': 'claw', 'baseChance': 0.25}, {'petal': 'sand', 'baseChance': 0.05}],
    "crab_mecha": [{'petal': 'mjolnir', 'baseChance': 1}, {'petal': 'laser', 'baseChance': 0.65}, {'petal': 'magnet', 'baseChance': 0.5}, {'petal': 'battery', 'baseChance': 0.05}],
    "dandelion": [{'petal': 'dandelion', 'baseChance': 0.3}],
    "digger": [{'petal': 'cutter', 'baseChance': 0.15}, {'petal': 'uranium', 'baseChance': 0.15}],
    "fire_ant_baby": [{'petal': 'broccoli', 'baseChance': 0.5}, {'petal': 'light', 'baseChance': 0.25}, {'petal': 'yucca', 'baseChance': 0.15}],
    "fire_ant_burrow": [{'petal': 'magnet', 'baseChance': 0.5}, {'petal': 'disc', 'baseChance': 0.3}],
    "fire_ant_egg": [{'petal': 'ant_egg', 'baseChance': 0.25}],
    "fire_ant_queen": [{'petal': 'ant_egg', 'baseChance': 0.5}, {'petal': 'basil', 'baseChance': 0.3}],
    "fire_ant_soldier": [{'petal': 'yucca', 'baseChance': 0.3}, {'petal': 'triangle', 'baseChance': 0.25}],
    "fire_ant_worker": [{'petal': 'yucca', 'baseChance': 0.15}, {'petal': 'corn', 'baseChance': 0.15}],
    "firefly": [{'petal': 'wing', 'baseChance': 0.25}, {'petal': 'bulb', 'baseChance': 0.25}, {'petal': 'battery', 'baseChance': 0.05}],
    "firefly_magic": [{'petal': 'battery', 'baseChance': 1}, {'petal': 'orb', 'baseChance': 0.28}],
    "fly": [{'petal': 'poo', 'baseChance': 0.25}, {'petal': 'wing', 'baseChance': 0.25}, {'petal': 'talisman', 'baseChance': 0.1}],
    "gambler": [{'petal': 'corruption', 'baseChance': 1}, {'petal': 'chip', 'baseChance': 0.25}, {'petal': 'card', 'baseChance': 0.25}, {'petal': 'dice', 'baseChance': 0.25}, {'petal': 'domino', 'baseChance': 0.25}],
    "garbage": [{'petal': 'poo', 'baseChance': 0.25}, {'petal': 'broccoli', 'baseChance': 0.25}],
    "ghost": [{'petal': 'basic', 'baseChance': 1}],
    "hornet": [{'petal': 'missile', 'baseChance': 0.25}, {'petal': 'orange', 'baseChance': 0.25}, {'petal': 'antennae', 'baseChance': 0.1}],
    "jellyfish": [{'petal': 'jelly', 'baseChance': 0.25}, {'petal': 'lightning', 'baseChance': 0.15}],
    "ladybug": [{'petal': 'light', 'baseChance': 0.25}, {'petal': 'rose', 'baseChance': 0.25}],
    "ladybug_dark": [{'petal': 'dahlia', 'baseChance': 0.25}, {'petal': 'yin_yang', 'baseChance': 0.1}],
    "ladybug_shiny": [{'petal': 'rose', 'baseChance': 1}, {'petal': 'dahlia', 'baseChance': 1}, {'petal': 'yggdrasil', 'baseChance': 0.5}],
    "leafbug": [{'petal': 'leaf', 'baseChance': 0.25}, {'petal': 'root', 'baseChance': 0.25}],
    "leafbug_shiny": [{'petal': 'root', 'baseChance': 1}, {'petal': 'golden_leaf', 'baseChance': 0.25}],
    "leech": [{'petal': 'fang', 'baseChance': 0.25}, {'petal': 'faster', 'baseChance': 0.25}],
    "mantis": [{'petal': 'peas', 'baseChance': 0.25}, {'petal': 'bur', 'baseChance': 0.25}],
    "mecha_flower": [{'petal': 'cog', 'baseChance': 1}, {'petal': 'mjolnir', 'baseChance': 1}, {'petal': 'battery', 'baseChance': 0.05}, {'petal': 'mimic', 'baseChance': 0.002}],
    "moth": [{'petal': 'wing', 'baseChance': 0.25}, {'petal': 'bulb', 'baseChance': 0.25}],
    "roach": [{'petal': 'antennae', 'baseChance': 0.25}, {'petal': 'lotus', 'baseChance': 0.05}],
    "rock": [{'petal': 'rock', 'baseChance': 0.15}, {'petal': 'heavy', 'baseChance': 0.05}, {'petal': 'moon', 'baseChance': 0.005}],
    "sandstorm": [{'petal': 'sand', 'baseChance': 0.15}, {'petal': 'glass', 'baseChance': 0.1}, {'petal': 'stick', 'baseChance': 0.05}],
    "scorpion": [{'petal': 'iris', 'baseChance': 0.25}, {'petal': 'pincer', 'baseChance': 0.25}],
    "shell": [{'petal': 'pearl', 'baseChance': 0.25}, {'petal': 'shell', 'baseChance': 0.15}, {'petal': 'magnet', 'baseChance': 0.01}],
    "silverfish": [{'petal': 'dust', 'baseChance': 0.75}, {'petal': 'clay', 'baseChance': 0.25}],
    "spider": [{'petal': 'faster', 'baseChance': 0.25}, {'petal': 'web', 'baseChance': 0.25}, {'petal': 'third_eye', 'baseChance': 0.01}],
    "spider_hel": [{'petal': 'card', 'baseChance': 0.1}, {'petal': 'mark', 'baseChance': 0.01}, {'petal': 'third_eye', 'baseChance': 0.01}],
    "spider_mecha": [{'petal': 'mjolnir', 'baseChance': 1}, {'petal': 'electric_web', 'baseChance': 0.25}, {'petal': 'goggles', 'baseChance': 0.1}, {'petal': 'battery', 'baseChance': 0.05}],
    "sponge": [{'petal': 'sponge', 'baseChance': 0.25}, {'petal': 'coral', 'baseChance': 0.1}],
    "square": [{'petal': 'square', 'baseChance': 1}],
    "starfish": [{'petal': 'starfish', 'baseChance': 0.25}, {'petal': 'sand', 'baseChance': 0.05}, {'petal': 'salt', 'baseChance': 0.05}],
    "termite_baby": [{'petal': 'carrot', 'baseChance': 0.25}, {'petal': 'relic', 'baseChance': 0.05}],
    "termite_egg": [{'petal': 'ant_egg', 'baseChance': 0.25}, {'petal': 'amulet', 'baseChance': 0.05}],
    "termite_mound": [{'petal': 'soil', 'baseChance': 0.25}, {'petal': 'rubber', 'baseChance': 0.2}, {'petal': 'relic', 'baseChance': 0.15}],
    "termite_overmind": [{'petal': 'tomato', 'baseChance': 1}, {'petal': 'compass', 'baseChance': 1}, {'petal': 'relic', 'baseChance': 0.5}],
    "termite_soldier": [{'petal': 'bone', 'baseChance': 0.25}, {'petal': 'relic', 'baseChance': 0.05}],
    "termite_worker": [{'petal': 'plank', 'baseChance': 0.15}, {'petal': 'relic', 'baseChance': 0.05}],
    "tomb": [{'petal': 'ankh', 'baseChance': 1}, {'petal': 'dust', 'baseChance': 0.5}, {'petal': 'totem', 'baseChance': 0.25}],
    "wasp": [{'petal': 'missile', 'baseChance': 0.75}, {'petal': 'antennae', 'baseChance': 0.2}, {'petal': 'blood_stinger', 'baseChance': 0.1}],
    "wasp_hel": [{'petal': 'missile', 'baseChance': 0.75}, {'petal': 'chip', 'baseChance': 0.1}, {'petal': 'mark', 'baseChance': 0.01}],
    "wasp_mecha": [{'petal': 'mjolnir', 'baseChance': 1}, {'petal': 'mecha_missile', 'baseChance': 0.75}, {'petal': 'mecha_antennae', 'baseChance': 0.45}, {'petal': 'battery', 'baseChance': 0.05}],
    "worm": [{'petal': 'shovel', 'baseChance': 0.15}, {'petal': 'soil', 'baseChance': 0.1}],
}